import { craftingStyles } from "galadrielcss";
// Importing the CSS file generated by Galadriel.CSS
import "./page.css";

export default function Home() {
  const container = craftingStyles(() => ({
    border: "1px solid #f88e2b",
		boxSizing: "border-box",
		fontFamily: "'Montserrat', sans-serif",
		fontWeight: "400",
		display: "grid",
		gap: "10px",
		gridTemplateColumns: "repeat(3, 1fr)",
		gridTemplateRows: "1fr 2fr 2fr 1fr",
		gridTemplateAreas: 
			"'head head head' 'nav main main' 'nav content section' 'foot foot foot'",
		padding: "10px",
    height: "70%",
    width: "80%",
		maxPortraitTablets: {
			gridTemplateColumns: "1fr",
			gridTemplateRows: "10% 30% 30% 10%",
			gridTemplateAreas: 
				"'head' 'nav' 'main' 'content' 'section' 'foot'",
		}
  }));

	const header = craftingStyles(() => ({
		backgroundColor: "#C1FAFF",
		gridArea: "head",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
	}));

	const nav = craftingStyles(() => ({
		backgroundColor: "#F9F871",
		gridArea: "nav",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
	}));

	const main = craftingStyles(() => ({
		backgroundColor: "#faae66",
		gridArea: "main",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
	}));

	const content = craftingStyles(() => ({
		backgroundColor: "#86DB82",
		gridArea: "content",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
	}));

	const section = craftingStyles(() => ({
		backgroundColor: "#eb9696",
		gridArea: "section",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
	}));

	const footer = craftingStyles(() => ({
		backgroundColor: "#7adac8",
		gridArea: "foot",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
	}));

  return <div className={container}>
		<header className={header}>Header</header>
		<nav className={nav}>Sidebar</nav>
		<main className={main}>Main</main>
		<div className={content}>Content</div>
		<div className={section}>Content</div>
		<footer className={footer}>Footer</footer>
	</div>;
}
